[package]
name = "validator-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[workspace]

[dependencies]
wasm-bindgen = "0.2"
serde_json = "1"
js-sys = "0.3"
regex = "1"
chrono = "0.4"
